authentication/urls.py
from django.urls import path
from authentication.views import login, logout

app_name = 'authentication'

urlpatterns = [
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
]

light_cones/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include('main.urls')),
    path('auth/', include('authentication.urls')),
]

main/urls.py
from django.urls import path
from main.views import add_light_cone, login_user, logout_user, \
    register, show_main, show_json, show_json_by_id, show_xml, show_xml_by_id, \
    get_item_json, add_item_ajax, create_product_flutter

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('add_light_cone/', add_light_cone, name='add_light_cone'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name="login"),
    path('logout/', logout_user, name="logout"),
    path('json_ajax/', get_item_json, name='get_item_json'),
    path('add_light_cone_ajax/', add_item_ajax, name='add_item_ajax'),
    path('create-flutter/', create_product_flutter, name='create_product_flutter'),
]

authentication/models.py
from django.db import models

# Create your models here.

light_cones/main/models.py
from django.db import models

# Create your models here.
class Item(models.Model):
    name = models.CharField(max_length=255)
    amount = models.IntegerField()
    description = models.TextField()
    rarity = models.IntegerField()
    path = models.CharField(max_length=255)

main/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
class Item(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    amount = models.IntegerField()
    description = models.TextField()
    rarity = models.IntegerField()
    path = models.CharField(max_length=255)

main/forms.py
from django.forms import ModelForm
from main.models import Item

class ItemForm(ModelForm):
    class Meta:
        model = Item
        fields = ["name", "amount", "description", "rarity", "path"]

authentication/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt

@csrf_exempt
def login(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(username=username, password=password)
    if user is not None:
        if user.is_active:
            auth_login(request, user)
            # Status login sukses.
            return JsonResponse({
                "username": user.username,
                "status": True,
                "message": "Login sukses!"
                # Tambahkan data lainnya jika ingin mengirim data ke Flutter.
            }, status=200)
        else:
            return JsonResponse({
                "status": False,
                "message": "Login gagal, akun dinonaktifkan."
            }, status=401)

    else:
        return JsonResponse({
            "status": False,
            "message": "Login gagal, periksa kembali email atau kata sandi."
        }, status=401)

@csrf_exempt
def logout(request):
    username = request.user.username

    try:
        auth_logout(request)
        return JsonResponse({
            "username": username,
            "status": True,
            "message": "Logout berhasil!"
        }, status=200)
    except:
        return JsonResponse({
        "status": False,
        "message": "Logout gagal."
        }, status=401)

main/views.py
import datetime
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect
from django.http import HttpRequest, HttpResponse, \
    HttpResponseRedirect, HttpResponseNotFound
from main.forms import ItemForm
from django.urls import reverse
from main.models import Item
from django.core import serializers
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse

# Create your views here.
@login_required(login_url='/main/login')
def show_main(request: HttpRequest):
    light_cone_list = Item.objects.filter(user=request.user)

    context = {
        'light_cone_list': light_cone_list
    }

    return render(request, "main.html", context)

def add_light_cone(request: HttpRequest):
    form = ItemForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        product = form.save(commit=False)
        product.user = request.user
        product.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form}
    return render(request, "add_light_cone.html", context)

def show_xml(request: HttpRequest):
    data = Item.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request: HttpRequest):
    data = Item.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request: HttpRequest, id):
    data = Item.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request: HttpRequest, id):
    data = Item.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def register(request: HttpRequest):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('main:login')
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request: HttpRequest):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("main:show_main")) 
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
    context = {}
    return render(request, 'login.html', context)

def logout_user(request: HttpRequest):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response

def get_item_json(request: HttpRequest):
    item = Item.objects.all()
    return HttpResponse(serializers.serialize('json', item))

@csrf_exempt
def add_item_ajax(request: HttpRequest):
    if request.method == 'POST':
        name = request.POST.get("name")
        amount = request.POST.get("amount")
        description = request.POST.get("description")
        rarity = request.POST.get("rarity")
        path = request.POST.get("path")
        user = request.user

        new_item = Item(name=name, amount=amount, description=description, rarity=rarity, path=path, user=user)
        new_item.save()

        return HttpResponse(b"CREATED", status=201)

    return HttpResponseNotFound()

@csrf_exempt
def create_product_flutter(request):
    if request.method == 'POST':
        
        data = json.loads(request.body)

        new_product = Product.objects.create(
            user = request.user,
            name = data["name"],
            price = int(data["price"]),
            description = data["description"]
        )

        new_product.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

main/templates/add_light_cone.html
{% extends 'base.html' %} 

{% block content %}
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand me-auto mb-2 mb-lg-0" href="#">Light Cone Inventory</a>
    <a class="nav-link active" href="logout/">Logout</a>
  </div>
</nav>

<form method="POST">
    {% csrf_token %}
    <div class="flex-table">
      <h3>Add New Light Cone</h3>
      <div>
        <table>
            {{ form.as_table }}
            <tr>
                <td></td>
                <td>
                    <input type="submit" value="Add Light Cone"/>
                </td>
            </tr>
        </table>
      </div>
    </div>
</form>

<style>
  .flex-table {
    display: flex;
    justify-content: center;
    flex-direction: column;
    text-align: center;
  }

  .flex-table > * {
    display: flex;
    flex: 1 1 0;
    justify-content: center;
  }
</style>
{% endblock %}

main/templates/login.html
{% extends 'base.html' %}

{% block meta %}
    <title>Login</title>
{% endblock meta %}

{% block content %}
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand me-auto mb-2 mb-lg-0" href="#">Light Cone Inventory</a>
    </div>
  </nav>

<div class = "login">
    <div class="flex-table">
        <h3>Login</h3>
        <form method="POST" action="">
            {% csrf_token %}
            <table>
                <tr>
                    <td>Username: </td>
                    <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
                </tr>
                        
                <tr>
                    <td>Password: </td>
                    <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
                </tr>
            </table>
            <input class="btn login_btn" type="submit" value="Login">
        </form>

        {% if messages %}
            <ul>
                {% for message in messages %}
                    <li>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}     
            
        Don't have an account yet? <a href="{% url 'main:register' %}">Register Now</a>
    </div>
</div>

<style>
    .flex-table {
        display: flex;
        justify-content: center;
        flex-direction: column;
        text-align: center;
    }

    .flex-table > * {
        display: flex;
        flex: 1 1 0;
        justify-content: center;
    }
</style>

{% endblock content %}

main/templates/main.html
{% extends 'base.html' %}

{% block content %}
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand me-auto mb-2 mb-lg-0" href="#">Light Cone Inventory</a>
    <a class="nav-link active" href="logout/">Logout</a>
  </div>
</nav>

<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
      <div class="modal-content">
          <div class="modal-header">
              <h1 class="modal-title fs-5" id="exampleModalLabel">Add New Light Cone</h1>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
              <form id="form" onsubmit="return false;">
                  {% csrf_token %}
                  <div class="mb-3">
                      <label for="name" class="col-form-label">Name:</label>
                      <input type="text" class="form-control" id="name" name="name"></input>
                  </div>
                  <div class="mb-3">
                      <label for="amount" class="col-form-label">Amount:</label>
                      <input type="number" class="form-control" id="amount" name="amount"></input>
                  </div>
                  <div class="mb-3">
                      <label for="description" class="col-form-label">Description:</label>
                      <textarea class="form-control" id="description" name="description"></textarea>
                  </div>
                  <div class="mb-3">
                      <label for="rarity" class="col-form-label">Rarity:</label>
                      <input type="number" class="form-control" id="rarity" name="rarity"></input>
                  </div>
                  <div class="mb-3">
                      <label for="path" class="col-form-label">Path:</label>
                      <input type="text" class="form-control" id="path" name="path"></input>
                  </div>
              </form>
          </div>
          <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
              <button type="button" class="btn btn-primary" id="button_add" data-bs-dismiss="modal" onclick="addLightConeAJAX()">Add Light Cone</button>
          </div>
      </div>
  </div>
</div>

<div class="p-2">
  <table id="display-table"></table>

  <a href="add_light_cone/">
    <button>Add light cone</button>
  </a>

  <br>

  <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">Add Light Cone by AJAX</button>
</div>

<style>
  table, tr > * {
    border: 1px solid black;
  }

  table {
    border-collapse: separate;
    border-spacing: 4px 4px;
  }

  tr > * {
    padding: 4px;
  }
</style>

<script>
  function addLightConeAJAX() {
    const formElement = document.getElementById("form");

    fetch("{% url 'main:add_item_ajax' %}", {
      method: "POST",
      body: new FormData(formElement)
    }).then(displayLightCones);

    formElement.reset();
    return false;
  }

  function addTableRow(data) {
    const displayTable = document.getElementById("display-table");

    const tr = document.createElement("tr");

    const nameTd = document.createElement("td");
    const amountTd = document.createElement("td");
    const rarityTd = document.createElement("td");
    const pathTd = document.createElement("td");
    const descTd = document.createElement("td");
    
    const name = document.createTextNode(data.name);
    const amount = document.createTextNode(data.amount);
    const rarity = document.createTextNode(data.rarity);
    const path = document.createTextNode(data.path);
    const desc = document.createTextNode(data.description);

    nameTd.appendChild(name);
    amountTd.appendChild(amount);
    rarityTd.appendChild(rarity);
    pathTd.appendChild(path);
    descTd.appendChild(desc);

    tr.appendChild(nameTd);
    tr.appendChild(amountTd);
    tr.appendChild(rarityTd);
    tr.appendChild(pathTd);
    tr.appendChild(descTd);

    displayTable.appendChild(tr);
  }

  function displayLightCones() {
    document.getElementById("display-table").innerHTML = "<tr>\n<th>Name</th>\n<th>Amount</th>\n<th>Rarity</th>\n<th>Path</th>\n<th>Description</th>\n</tr>";
    getLightCones().then(results => {
      for (let i = 0; i < results.length; i++) {
        const fields = results[i].fields;
        addTableRow(fields);
      }
    });
  }
  
  async function getLightCones() {
    const origin =  window.location.origin;
    const response = await fetch(`${origin}/main/json_ajax/`);
    const jsonObject = await response.json();
    return jsonObject;
  }
  
  displayLightCones();
</script>
{% endblock content %}

main/templates/register.html
{% extends 'base.html' %}

{% block meta %}
    <title>Register</title>
{% endblock meta %}

{% block content %}
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand me-auto mb-2 mb-lg-0" href="#">Light Cone Inventory</a>
    </div>
  </nav>

<div class = "login">
    <div class="flex-table">
    
        <h1>Register</h1>

        <form method="POST" >  
            {% csrf_token %}  
            <table>  
                {{ form.as_table }}  
                <tr>  
                    <td></td>
                    <td><input type="submit" name="submit" value="Daftar"/></td>  
                </tr>  
            </table>  
        </form>

        {% if messages %}  
            <ul>   
                {% for message in messages %}  
                    <li>{{ message }}</li>  
                    {% endfor %}  
            </ul>
        {% endif %}
    </div>

</div>

<style>
    .flex-table {
        display: flex;
        justify-content: center;
        flex-direction: column;
    }

    .flex-table > * {
        display: flex;
        flex: 1 1 0;
        justify-content: center;
    }
</style>

{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        {% block meta %}
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        {% endblock meta %}
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    </head>

    <body>
        {% block content %}
        {% endblock content %}
    </body>
</html>